// Generated by https://quicktype.io

export interface SetDetailsData {
    setID: number;
    number: string;
    numberVariant: number;
    name: string;
    year: number;
    theme: string;
    themeGroup: string;
    subtheme: string;
    category: string;
    released: boolean;
    pieces: number;
    image: Image;
    bricksetURL: string;
    collection: AgeRange;
    collections: Collections;
    LEGOCom: LEGOCOM;
    rating: number;
    reviewCount: number;
    packagingType: string;
    availability: string;
    instructionsCount: number;
    additionalImageCount: number;
    ageRange: AgeRange;
    dimensions: Dimensions;
    barcode: Barcode;
    extendedData: ExtendedData;
    lastUpdated: string;
}

export interface LEGOCOM {
    US: CA;
    UK: CA;
    CA: CA;
    DE: CA;
}

export interface CA {
    retailPrice: number;
    dateFirstAvailable: string;
}

export interface AgeRange {
}

export interface Barcode {
    EAN: string;
}

export interface Collections {
    ownedBy: number;
    wantedBy: number;
}

export interface Dimensions {
    height: number;
    width: number;
    depth: number;
}

export interface ExtendedData {
    tags: string[];
    description: string;
}

export interface Image {
    thumbnailURL: string;
    imageURL: string;
}
