// Generated by https://quicktype.io

export interface Theme {
    theme: string;
    setCount: number;
    subthemeCount: number;
    yearFrom: number;
    yearTo: number;
}

export interface SubTheme {
    'theme': string,
    'subtheme': string,
    'setCount': number,
    'yearFrom': number,
    'yearTo': number
}
